name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Install and build release
      uses: actions/setup-node@v4
      with:
        node-version: 21
    - run: npm install
    - run: npm run build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./built/packaged s3://chibitronics --delete
